# site settings
title: MoneyStack
company: MoneyStack, Inc.
copyright_year: 2019
copyright_statement: All rights reserved.
slogan: Let's talk about money
email: hello@moneystack.com
description: MoneyStack is a personal finance app that helps you talk about money with your significant other, family, and friends in a safe, easy, and truthful way without having to use spreadsheets or do any math.
baseurl: # the subpath of your site, e.g. /blog
url:
author:
street_address: '725 River Road, #32106'
city: Edgewater
state: NJ
zip_code: '07020-1171'
country: United States of America
phone: +1 (724) 281-3487

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
