# site settings
title: MoneyStack
company: MoneyStack, Inc.
copyright_year: 2019
copyright_statement: All rights reserved.
slogan: The DIY Financial Planning App
email: hello@moneystack.com

description: 'MoneyStack is a DIY financial planning app for everyone.'
description2: 'Use it instead of spreadsheets to quickly build error-free scenarios and collaborate with your significant other as you plan for big expenses and life-events together. If you get stuck, you can find a vetted financial advisor in our marketplace and invite them into your online workspace to help you.'
baseurl: # the subpath of your site, e.g. /blog
url:
author:
street_address: '725 River Road #32106'
city: Edgewater
state: NJ
zip_code: '07020-1171'
country: USA
phone: +1 (724) 281-3487

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed


ga_trackingId: 'UA-134660224-1'
